name: Deploy from Obsidian notes

on:
  push:
    branches:
      - main

jobs:
  publish_job:
    runs-on: ubuntu-latest
    name: Publish Obsidian notes to Github pages
    steps:
      - uses: actions/checkout@v3
      - uses: ./github/actions/
        with:
          vault-path: vault
          github-token: ${{ secrets.GITHUB_TOKEN }}
